---
title: Lauren Gallo
timezone: America/New_York
collections:
  news:
    title: News
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://laurenmgallo.com
gems:
- jekyll-paginate
- jekyll-seo-tag
paginate: 3
paginate_path: "/page:num/"
hilighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "<!--more-->"
email: your-email@domain.com
exclude:
- ".gitignore"
description: Lauren Gallo - Brand Strategy, Marketing, Content, Curator
baseurl: 
destination: "./build"
sass:
  style: compressed
permalink: pretty
info: " Brand Strategy   |    Marketing   |   Content   |   Curator"
asset: "/uploads/IMG_4762.JPG.jpeg"
